const SET_LOADING = "SET_LOADING";
const SET_ERROR = "SET_ERROR";
const SET_DATA = "SET_DATA";
const SET_USER_DETAILS = "SET_USER_DETAILS";
const RESET_USER_DETAILS = "RESET_USER_DETAILS";
const INITIAL_USERS_COUNT = 20;

export default {
  SET_ERROR,
  SET_LOADING,
  SET_DATA,
  SET_USER_DETAILS,
  RESET_USER_DETAILS,
  INITIAL_USERS_COUNT,
};
