const SET_LOADING = "SET_LOADING";
const SET_ERROR = "SET_ERROR";
const SET_ORGANISATIONS = "SET_ORGANISATIONS";
const SET_ORGANISATION_DETAILS = "SET_ORGANISATION_DETAILS";

export default {
  SET_ERROR,
  SET_LOADING,
  SET_ORGANISATIONS,
  SET_ORGANISATION_DETAILS,
};
